_target_: gfmrag.kg_construction.openie_model.LLMOPENIEModel
llm_api: ${oc.env:GFMRAG_CHAT_PROVIDER,openai}
model_name: ${oc.env:GFMRAG_CHAT_MODEL_NAME,gpt-4o-mini}
base_url: ${oc.env:GFMRAG_CHAT_BASE_URL,null}
api_key: ${oc.env:GFMRAG_CHAT_KEY,null}
max_ner_tokens: ${oc.env:GFMRAG_OPENIE_NER_TOKENS,800}
max_triples_tokens: ${oc.env:GFMRAG_OPENIE_TRIPLES_TOKENS,8192}
max_retries: ${oc.env:GFMRAG_OPENIE_MAX_RETRIES,3}
retry_delay: ${oc.env:GFMRAG_OPENIE_RETRY_DELAY,1.0}
request_timeout: ${oc.env:GFMRAG_OPENIE_TIMEOUT,300}
